apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-mecanica-api-configmap
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  AllowedHosts: "*"
  EmailSettings__Email: "noreplyoficinamecanica@gmail.com"
  EmailSettings__Host: "smtp.gmail.com"
  EmailSettings__Port: "587"
