apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-mecanica-api
spec:
  selector:
    matchLabels:
      app: oficina-mecanica-api
  template:
    metadata:
      labels:
        app: oficina-mecanica-api
    spec:
      containers:
      - name: oficina-mecanica-api
        image: oficina:local
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: oficina-mecanica-api-configmap
        - secretRef:
            name: oficina-mecanica-api-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
          limits:
            memory: "256Mi"
            cpu: "600m"
        ports:
        - containerPort: 8080
